In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
import keras as k
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)


Using TensorFlow backend.


In [2]:
data = pd.read_csv('D:\Python\Online Contest\Elieptic Seizure Recognition.csv')

print(data.head())
print(data.describe())

    X1   X2   X3   X4   X5   X6   X7   X8   X9  X10  X11  X12  X13  X14  X15  \
0  135  190  229  223  192  125   55   -9  -33  -38  -10   35   64  113  152   
1  386  382  356  331  320  315  307  272  244  232  237  258  212    2 -267   
2  -32  -39  -47  -37  -32  -36  -57  -73  -85  -94  -99  -94  -96 -104 -103   
3 -105 -101  -96  -92  -89  -95 -102 -100  -87  -79  -72  -68  -74  -80  -83   
4   -9  -65  -98 -102  -78  -48  -16    0  -21  -59  -90 -103  -84  -43   -9   

   X16  X17   X18   X19   X20  X21  X22  X23  X24  X25  X26  X27  X28  X29  \
0  164  127    50   -47  -121 -138 -125 -101  -50   11   39   24   48   64   
1 -605 -850 -1001 -1109 -1090 -967 -746 -464 -152  118  318  427  473  485   
2  -92  -75   -69   -69   -53  -37  -14  -10  -39  -78 -102  -98  -80  -54   
3  -73  -68   -61   -58   -59  -64  -79  -84  -97  -94  -84  -77  -75  -72   
4    3  -21   -60   -96  -103  -75  -29   14   55   78   73   28  -13  -43   

   X30  X31  X32  X33  X34  X35  X36  X37  X38  X3

In [3]:
data.isnull().any()

X1      False
X2      False
X3      False
X4      False
X5      False
X6      False
X7      False
X8      False
X9      False
X10     False
X11     False
X12     False
X13     False
X14     False
X15     False
X16     False
X17     False
X18     False
X19     False
X20     False
X21     False
X22     False
X23     False
X24     False
X25     False
X26     False
X27     False
X28     False
X29     False
X30     False
X31     False
X32     False
X33     False
X34     False
X35     False
X36     False
X37     False
X38     False
X39     False
X40     False
X41     False
X42     False
X43     False
X44     False
X45     False
X46     False
X47     False
X48     False
X49     False
X50     False
X51     False
X52     False
X53     False
X54     False
X55     False
X56     False
X57     False
X58     False
X59     False
X60     False
X61     False
X62     False
X63     False
X64     False
X65     False
X66     False
X67     False
X68     False
X69     False
X70     False
X71     False
X72   

In [4]:
data.mean(axis=0)

X1     -11.581391
X2     -10.911565
X3     -10.187130
X4      -9.143043
X5      -8.009739
X6      -7.003478
X7      -6.502087
X8      -6.687130
X9      -6.558000
X10     -6.168435
X11     -5.827478
X12     -6.042174
X13     -6.687304
X14     -7.088870
X15     -7.211217
X16     -7.088261
X17     -6.806696
X18     -6.744696
X19     -6.484783
X20     -6.448435
X21     -6.355391
X22     -6.543130
X23     -6.884348
X24     -6.883217
X25     -6.118870
X26     -5.159130
X27     -4.785652
X28     -4.874783
X29     -5.393565
X30     -5.935478
X31     -6.349913
X32     -6.212522
X33     -5.859826
X34     -5.299826
X35     -4.955652
X36     -5.278087
X37     -6.162261
X38     -7.316609
X39     -7.998522
X40     -7.818870
X41     -6.964087
X42     -5.773826
X43     -4.700783
X44     -4.143826
X45     -4.546087
X46     -5.532000
X47     -6.670435
X48     -7.702348
X49     -7.894696
X50     -8.081391
X51     -7.818174
X52     -7.693913
X53     -7.210783
X54     -6.653391
X55     -6.183130
X56     -5

In [5]:
train_x = data.iloc[:int(0.6*data.shape[0]),:data.shape[1]-1]
train_y = data.iloc[:int(0.6*data.shape[0]),data.shape[1]-1]


test_x = data.iloc[int(0.6*data.shape[0]):,:data.shape[1]-1]
test_y = data.iloc[int(0.6*data.shape[0]):,data.shape[1]-1]

print(train_x.head())
print(test_x.head())


    X1   X2   X3   X4   X5   X6   X7   X8   X9  X10  X11  X12  X13  X14  X15  \
0  135  190  229  223  192  125   55   -9  -33  -38  -10   35   64  113  152   
1  386  382  356  331  320  315  307  272  244  232  237  258  212    2 -267   
2  -32  -39  -47  -37  -32  -36  -57  -73  -85  -94  -99  -94  -96 -104 -103   
3 -105 -101  -96  -92  -89  -95 -102 -100  -87  -79  -72  -68  -74  -80  -83   
4   -9  -65  -98 -102  -78  -48  -16    0  -21  -59  -90 -103  -84  -43   -9   

   X16  X17   X18   X19   X20  X21  X22  X23  X24  X25  X26  X27  X28  X29  \
0  164  127    50   -47  -121 -138 -125 -101  -50   11   39   24   48   64   
1 -605 -850 -1001 -1109 -1090 -967 -746 -464 -152  118  318  427  473  485   
2  -92  -75   -69   -69   -53  -37  -14  -10  -39  -78 -102  -98  -80  -54   
3  -73  -68   -61   -58   -59  -64  -79  -84  -97  -94  -84  -77  -75  -72   
4    3  -21   -60   -96  -103  -75  -29   14   55   78   73   28  -13  -43   

   X30  X31  X32  X33  X34  X35  X36  X37  X38  X3

In [19]:
from sklearn.decomposition import PCA


pca = PCA(50)
pca.fit(train_x)
print(pca.explained_variance_ratio_)

sum(pca.explained_variance_ratio_)

[ 0.0590281   0.05265619  0.04934044  0.04579488  0.04493009  0.0432764
  0.04080389  0.0400245   0.03722498  0.03422654  0.03366453  0.03113413
  0.02931375  0.02754322  0.02508764  0.02456347  0.02272754  0.02121165
  0.02085629  0.02010052  0.01885424  0.01776289  0.01762333  0.01734027
  0.0161938   0.01588723  0.01505692  0.01464357  0.01398225  0.01345013
  0.01321758  0.01224197  0.01221667  0.01147034  0.01048373  0.00951901
  0.00773499  0.00696957  0.00605918  0.00505133  0.00488596  0.0044012
  0.00384839  0.00292704  0.00255394  0.00224275  0.00214375  0.00175104
  0.00159325  0.00153112]


0.98714620686834098

In [30]:
train_redX = pca.transform(train_x)


#pd.DataFrame(train_redX).head()

train_redX = pd.DataFrame(train_redX)

In [40]:
#SVM

from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import validation_curve

param_range = np.logspace(-6,-1,5)
train_scores, valid_scores = validation_curve(SVC(verbose=1,kernel='rbf'),train_redX,train_y,param_name='gamma',param_range=param_range)



[LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM]

In [42]:
print(train_scores)

print(valid_scores)

[[ 0.71754729  0.71521739  0.72006086]
 [ 0.99869537  0.99804348  0.99934797]
 [ 1.          1.          1.        ]
 [ 1.          1.          1.        ]
 [ 1.          1.          1.        ]]
[[ 0.59539331  0.61173913  0.6076555 ]
 [ 0.3289874   0.32043478  0.32970857]
 [ 0.20860495  0.2073913   0.20878643]
 [ 0.20469361  0.20434783  0.20443671]
 [ 0.20469361  0.20434783  0.20443671]]


In [53]:
#Adaboost

from sklearn.ensemble import AdaBoostClassifier

params = {'n_estimators':[25,50,100,200]}
clf2 = GridSearchCV(AdaBoostClassifier(),param_grid=params)

clf2.fit(train_redX,train_y)
print(clf2.score(train_redX,train_y))



0.542173913043


In [57]:
clf3 = AdaBoostClassifier(n_estimators = 50)

clf3.fit(train_redX,train_y)

print(clf3.score(train_redX,train_y))   # on increasing n_estimators model gets better for validation set



0.531014492754


In [63]:
print(clf3.score(test_x,test_y))
print(clf3.get_params)
print(clf2.score(test_x,test_y))
print(clf2.best_params_)


0.526304347826
<bound method BaseEstimator.get_params of AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=50, random_state=None)>
0.544782608696
{'n_estimators': 200}


In [64]:
#Random Forests
from sklearn.ensemble import RandomForestClassifier

params = {'n_estimators':[5,10,20,50],'max_depth':[1,5,10,25,50]}
clf4 = GridSearchCV(RandomForestClassifier(),param_grid = params)
clf4.fit(train_redX,train_y)

print(clf4.score(train_redX,train_y))

print(clf4.best_params_)   #on increasing n_estimators model gets better and generalized.

0.995217391304
{'max_depth': 25, 'n_estimators': 50}


In [66]:
clf3 = AdaBoostClassifier(n_estimators = 1000)
clf3.fit(train_redX,train_y)

print(clf3.score(train_redX,train_y))

0.554347826087


In [72]:
#Neural Network aka MLP
from sklearn.neural_network import MLPClassifier

clf5 = MLPClassifier(hidden_layer_sizes=(200,))
clf5.fit(train_redX,train_y)

print(clf5.score(train_redX,train_y))
print(clf5.score(test_x,test_y))                        #on increasing the hidden layer size
                                                        #model gets overfit and validation score decreases


0.792608695652
0.511956521739


In [ ]:
#Random Forests Give the best results

#XGBOOST

